apps/usuario/urls.py
from django.urls import path
from django.urls import include, re_path
from django.contrib.auth.decorators import login_required

#Usuario Login

#Perfil Usuario
from apps.usuario.view.views_perfil import LoginPerfilView,DashboardView,LogoutView,manual,\
    PerfilUsuarioListarView

    #LoginPerfilView,DashboardView,LogoutView,manual,UsuarioPerfilDetalleView1,UsuarioPerfilDetalleView,UsuarioPerfilEditarView,passwordusuarioview

app_name = 'usuario'

urlpatterns = [
    #Login
    #path('index/', LoginView.as_view(), name='index'),
    path('', LoginPerfilView.as_view(), name='index'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('logout/', LogoutView, name='logout'),
    #info ayuda
    path('menu/', manual, name='menu'),

    #Perfil de Usuario
    path('perfil/listar/', PerfilUsuarioListarView.as_view(), name='listar_perfil'),



]

proyectosipyet/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.usuario.urls', namespace="usuario")),
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL,
                                       document_root=settings.MEDIA_ROOT)

apps/usuario/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.utils import timezone
import time
from apps.usuario.templatetags.utils import ROLES

class EstadoModel(models.Model):
    #id = models.UUIDField('id', default=uuid.uuid4, primary_key=True, unique=True, null=False, blank=False,editable=False)
    descripcion = models.TextField('descripcion', blank=True, null=True)
    direccion_ip = models.GenericIPAddressField(blank=True, null=True)
    creacion = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    modificacion = models.DateTimeField(auto_now=True, blank=True, null=True)
    estado = models.BooleanField(default=True)
    #uc = models.CharField(max_length=100, blank=True,null=True)
    #uc = models.ForeignKey(Usuario,blank=True,null=True,on_delete=models.CASCADE)#usuario creo
    uc = models.IntegerField(blank=True, null=True)
    #um =models.ForeignKey(User,on_delete=models.CASCADE)#usuario modifico
    #um = models.CharField(max_length=100, blank=True,null=True)
    um = models.IntegerField(blank=True,null=True)

    class Meta:
        abstract = True

class UserManager(BaseUserManager):
    def create_user(self, usuario, email, password):
        if not email:
            raise ValueError('El Email o Correo Electronico  es obligatorio')
        user = self.model(email=self.normalize_email(email))
        user.usuario = usuario
        user.set_password(password)
        user.is_staff = True
        user.save(using=self._db)
        return user

    def create_superuser(self, usuario, email, password):
        user = self.create_user(usuario, email, password)
        user.is_active = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

def img_url(self, filename):
    hash_ = int(time.time())
    return "%s/%s/%s" % ("media", hash_, filename)

class Usuario(AbstractBaseUser, PermissionsMixin):
    usuario = models.CharField('Usuario', max_length=15, unique=True)
    email = models.EmailField('Correo Electronico', max_length=50, unique=True)
    observaciones = models.TextField(blank=True, null=True)
    # id = models.UUIDField('id', default=uuid.uuid4, primary_key=True, unique=True,null=False, blank=False, editable=False)
    nombre = models.CharField('Nombres', max_length=50)
    apellido = models.CharField('Apellidos', max_length=50)
    # Fecha de Registro
    date_joined = models.DateTimeField(default=timezone.now)

    objects = UserManager()

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'usuario'
    REQUIRED_FIELDS = ['email', ]

    def get_short_name(self):
        return self.usuario

    def get_full_name(self):
        return (self.usuario)

    def has_perm(self, perm, obj=None):
        "¿El usuario cuenta con los permisos en especificos?"
        return True

    def has_module_perms(self, app_label):
        "¿El usuario cuenta con los permisos para ver una app en especificos?"
        return True

    def __unicode__(self):
        return "%s" % (self.usuario)

    #        return "%s %s" % (self.usuario, self.apellido)

    def __str__(self):
        return "%s" % (self.usuario)

    #        return "%s %s" % (self.usuario, self.apellido)

    class Meta:
        ordering = ['-is_active']
        verbose_name_plural = "Usuarios"

"""
    def save(self):
        super().save()
        img = Image.open(self.perfil_pic.path)
        if img.height > 400 or img.width > 400:
            output_size = (400, 400)
            img.thumbnail(output_size)
            img.save(self.perfil_pic.path)

    @property
    def is_staff(self):
        "¿El usuario es staff(no super-usuario)?"
        return self.is_staff

    @property
    def is_active(self):
        "¿El usuario esta activo?"
        return self.is_active
"""

class Perfil(Usuario):
    roles = models.CharField(max_length=20, choices=ROLES, default='Usuario')
    perfil_img = models.ImageField(verbose_name='Imagen de Perfil', upload_to=img_url, blank=True, null=True)
    #perfil_pic = models.FileField(max_length=1000, upload_to=img_url, null=True, blank=True)
    # perfil_pic = models.ImageField(upload_to=img_url, verbose_name='Imagen de Usuario',blank=True, null=True)

    # empleado = models.ForeignKey(ContratoEmpleado, blank=True, null=True, on_delete=models.CASCADE)
    # empleado = models.OneToOneField('rrhh.ContratoEmpleado', null=True, blank=True, unique=True,on_delete=models.CASCADE)
    direccion_ip = models.GenericIPAddressField(blank=True, null=True)
    estado = models.BooleanField(default=True)  # uc = models.ForeignKey(Usuario,on_delete=models.CASCADE)#usuario creo
    modificacion = models.DateTimeField(auto_now=True)  # , blank=True, null=True)
    uc = models.IntegerField(blank=True, null=True)
    um = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return '%s' % (self.usuario)

    class Meta:
        ordering = ['-is_active']
        verbose_name_plural = "Perfiles"

templates/sipyet/apps/usuario/index.html
{% extends "base/static/base_login.html" %}
<!--
{-% load staticfiles %}
-->
{% load static %}
{% block title %}Login{% endblock title %}
{% block content %}
    <div class="form-box" id="login-box">

        <div class="header">
            <a href="{% url 'usuario:index' %}">
                <img src="{% static 'img/banner.png' %}"/>
            </a>
        </div>

        <!--div class="center-block">
            {% if error %}
                <div class="alert alert-danger" class="alert alert-warning alert-dismissible fade show" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span></button>
                    <strong>Error! </strong>{{ message }}
                </div>
            {% endif %}
        </div-->

        <form id="login_form" method="post" autocomplete="off">
            {% csrf_token %}
            <div class="body bg-gray">
                <div class="row">
                    <div class="col-md-12">
                        <div class="input-group">
                                <span class="input-group-addon">
                                        <i class="fa fa-user"></i>
                                </span>
                            <input type="text" name="usuario" id="usuario" class="form-control" placeholder="Nombre de Usuario" autocomplete="off" />
                            <span class="error">{{form.usuario.errors}}</span>
                        </div>
                    </div>
                </div>
                <br/>
                <div class="row">
                    <div class="col-md-12">
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-lock"></i>
                            </div>
                            <input type="password" name="password" class="form-control" placeholder="Aqu&iacute; su Contrase&ntilde;a" autocomplete="off" />
                            <span class="error">{{form.password.errors}}</span>
                        </div>
                    </div>
                </div>
            </div>



            <div class="footer">
                <button type="submit" class="btn bg-olive btn-block">Ingresar</button>
                <p><a href="{% url 'usuario:dashboard' %}">Dashboard</a></p>
                <p><a href="{% url 'usuario:menu' %}">Menu</a></p>
            </div>
        </form>



        <div class="margin text-center">
            <span><script>document.write(new Date().getFullYear())</script> &copy; Sistema de Parqueo y Estacionamiento Tahuamanu</span>
        </div>

    </div>
{% endblock content %}
{% block jssextras %}
   <script type="text/javascript">
   $(function () {
       {% if error %}
           toastr["error"]("{{ message }}", "Aviso del Sistema")
       {% endif %}
       },)
    </script>

   <!--script type="text/javascript">
        jQuery(document).ready(function() {
            $("#usuario").focus();
            $("#login_form").validate({
                rules:{
                    usuario: {
                        required: true
                    },
                    clave: {
                        required: true
                    }
                },
                messages:{
                    usuario:{
                        required: "El nombre de usuario es requerido!"
                    },
                    clave:{
                        required: "La Contrase&ntilde;a es requerida!"
                    }
                },
                submitHandler: function(form) {
                    $.ajax({
                      type: "POST",
                      url: $("#login_form").attr("action"),
                      data: $("#login_form").serialize(),
                      dataType: "json",
                      success: function(datax){
                        if(datax.estado=="success"){
                            window.location.replace("/archivo/_principal/index");
                        }else{
                            toastr[datax.estado](datax.mensaje,'Aviso del Sistema');
                        }
                      }
                    }).done(function( msg ) {

                    }).fail(function( jqXHR, textStatus ) {
                        toastr.error("Fallo por error desconocido!!",'Aviso del Sistema');
                    });
                }
            });

        });
    </script-->
{% endblock jssextras %}