apps/usuario/urls.py
from django.urls import path
from django.urls import include, re_path
from django.contrib.auth.decorators import login_required

#Usuario Login

#Perfil Usuario
from apps.usuario.view.views_perfil import LoginPerfilView,DashboardView,LogoutView,manual,\
    PerfilUsuarioListarView

    #LoginPerfilView,DashboardView,LogoutView,manual,UsuarioPerfilDetalleView1,UsuarioPerfilDetalleView,UsuarioPerfilEditarView,passwordusuarioview

app_name = 'usuario'

urlpatterns = [
    #Login
    #path('index/', LoginView.as_view(), name='index'),
    path('', LoginPerfilView.as_view(), name='index'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('logout/', LogoutView, name='logout'),
    #info ayuda
    path('menu/', manual, name='menu'),

    #Perfil de Usuario
    path('perfil/listar/', PerfilUsuarioListarView.as_view(), name='listar_perfil'),



]

proyectosipyet/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.usuario.urls', namespace="usuario")),
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL,
                                       document_root=settings.MEDIA_ROOT)

templates/base/aside.html
<!--
{-% load staticfiles %}
-->
{% load static %}
<!-- Left side column. contains the logo and sidebar -->
<aside class="left-side sidebar-offcanvas">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <!--img src="{% static 'img/avatar5.png' %}" class="img-circle" alt="Imagen de Usuario"/-->
                <img src="{% static 'img/favicon.ico' %}" class="img-circle" alt="Imagen de Usuario"/>
            </div>
            <div class="pull-left info">
                <p>Hola, {{ user.nombre|capfirst }}</p>

                <a href="#"><i class="fa fa-circle text-success"></i> En l&iacute;nea</a>
            </div>
        </div>
        <!-- search form -->
        <form action="" method="POST" id="basic_search"
              name="basic_search" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="query" id="query" class="form-control"
                       placeholder="Buscar colecci&oacute;n..."/>
                <span class="input-group-btn">
                                <button type="submit" id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
                            </span>
            </div>
        </form>
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu">
            <li class="active">
                <a href="{% url 'usuario:dashboard' %}">
                    <i class="fa fa-dashboard"></i> <span>Inicio</span>
                </a>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-file-text"></i>
                    <span>Colecciones</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#" class="menu_load_panel" data="_colecciones/listar"><i
                            class="fa fa-angle-double-right"></i>Listar Colecciones</a></li>
                    <li><a href="#" id="nuevo_archivo_link" class="menu_load_panel" data="_colecciones/nuevo"
                           data_modal="true"><i class="fa fa-angle-double-right"></i>Agregar
                        Colecci&oacute;n</a></li>
                    <li><a href="#" class="menu_load_panel" data="_colecciones/search_view"><i
                            class="fa fa-angle-double-right"></i>B&uacute;squeda avanzada</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-male"></i>
                    <span>Autores</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#" class="menu_load_panel" data="_autores/listar_autores"><i
                            class="fa fa-angle-double-right"></i> Listar Autores</a></li>
                    <li><a href="#" id="nuevo_autor_link" class="menu_load_panel" data="_autores/nuevo_view"
                           data_id_modal="#divNuevoAutor" data_modal="true"><i
                            class="fa fa-angle-double-right"></i> Agregar nuevo Autor</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-map-marker"></i>
                    <span>Lugares</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#" class="menu_load_panel" data="_localidades/listar_localidades"><i
                            class="fa fa-angle-double-right"></i> Listar Lugares</a></li>
                    <li><a href="#" id="nuevo_localidad_link" class="menu_load_panel"
                           data="_localidades/nuevo_view" data_id_modal="#divNuevoLugar" data_modal="true"><i
                            class="fa fa-angle-double-right"></i> Agregar nuevo Lugar</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-filter"></i>
                    <span>Par&aacute;metros</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#" class="menu_load_panel" data="_tipoingresos/listar"><i
                            class="fa fa-angle-double-right"></i> Listar tipos de ingresos</a></li>
                    <li><a href="#" id="nuevo_tipo_ingreso_link" class="menu_load_panel"
                           data="_tipoingresos/nuevo" data_id_modal="#divNuevoTipo" data_modal="true"><i
                            class="fa fa-angle-double-right"></i> Agregar tipo de ingreso</a></li>
                    <li><a href="#" class="menu_load_panel" data="_tipos/listar_tipos"><i
                            class="fa fa-angle-double-right"></i> Listar tipos de colecciones</a></li>
                    <li><a href="#" id="nuevo_tipo_link" class="menu_load_panel" data="_tipos/nuevo_view"
                           data_id_modal="#divNuevoTipo" data_modal="true"><i
                            class="fa fa-angle-double-right"></i> Agregar tipo de colecci&oacute;n</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-users"></i>
                    <span>Usuarios</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li>
                        <a href="{% url 'usuario:listar_perfil' %}" class="menu_load_panel" data="#">
                            <i class="fa fa-angle-double-right"></i> Listar Perfil Usuarios
                        </a>
                    </li>

                    <li>
                        <a href="#" class="menu_load_panel" data="_usuarios/listar">
                            <i class="fa fa-angle-double-right"></i> Listar Usuarios
                        </a>
                    </li>
                    <li>
                        <a href="#" id="nuevo_usuario_link" class="menu_load_panel" data="_usuarios/nuevo"
                           data_modal="true">
                            <i class="fa fa-angle-double-right"></i> Agregar Usuario
                        </a>
                    </li>
                    <li><a href="#" class="menu_load_panel" data="_usuarios/change_pass"
                           data_id_modal="#divCPass" data_modal="true"><i class="fa fa-angle-double-right"></i>
                        Cambiar mi Contrase&ntilde;a</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-table"></i>
                    <span>Reportes</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#" class="menu_load_panel" data="_reportes/time_line"><i
                            class="fa fa-angle-double-right"></i> Linea de Tiempo</a></li>
                    <li><a href="#" class="menu_load_panel" data="_reportes/listar"><i
                            class="fa fa-angle-double-right"></i> Reportes personalizados</a></li>

                </ul>
            </li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>

templates/base/base.html
<!DOCTYPE html>
<html lang="es-BO">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Sistema de Parqueo y Estacionamiento Tahuamanu">
    <meta name="author" content="Ajerhy Inc">
    {% block css %}
    {% endblock css %}

    {% block csssextras %}
    {% endblock csssextras %}
</head>

<body class="skin-blue">

{% block content %}

{% endblock content %}

{% block js %}

{% endblock js %}

{% block jssextras %}

{% endblock jssextras %}

</body>

</html>

templates/base/footer.html
<footer class="box-footer">
    <div class="container">

    </div>
</footer>

<footer>
    <div class="footer">
        <div class="container-fluid"  id="myfooter">
            <div class="row">
                <div class="col-md-12">
                    <p class="copyright">
                        <strong>Copyright &copy;
                            <script>
                                document.write(new Date().getFullYear())
                            </script>
                            -Todos los derechos reservados <a href="#" target="_blank">Ajerhy Inc</a>.</strong>
                    </p>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/base/header.html
<!--
{-% load staticfiles %}
-->
{% load static %}
<!-- header logo: style can be found in header.less -->
<header class="header">
    <a href="{% url 'usuario:dashboard' %}" class="logo">
        <!--
        <img src="{% static 'img/archivos1.png' %}" class="img-rounded">
        -->
        <i class="fa fa-anchor"></i>
        <span>SipyeT</span></a>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>
        <div class="navbar-right">
            <ul class="nav navbar-nav">
                <!-- Messages: style can be found in dropdown.less-->

                <!-- Notifications: style can be found in dropdown.less -->

                <!-- Tasks: style can be found in dropdown.less -->

                <!-- User Account: style can be found in dropdown.less -->
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="glyphicon glyphicon-user"></i>
                        <span>admin<i class="caret"></i></span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header bg-light-blue">
                            <!--img src="{% static 'img/avatar5.png' %}" class="img-circle" alt="Imagen de Usuario"/-->
                            <img src="{% static 'img/favicon.ico' %}" class="img-circle" alt="Imagen de Usuario"/>
                            <p>
                                {{ user.nombre|capfirst }} {{ user.apellido|capfirst }} <small>
                                {{ user.roles }} </small>
                            </p>
                        </li>
                        <!-- Menu Body -->
                        <!--
<li class="user-body">
                            <div class="col-xs-4 text-center">
                                <a href="#">Followers</a>
                            </div>
                            <div class="col-xs-4 text-center">
                                <a href="#">Sales</a>
                            </div>
                            <div class="col-xs-4 text-center">
                                <a href="#">Friends</a>
                            </div>
                        </li>
-->
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="#" data="_usuarios/change_pass" data_id_modal="#divCPass" data_modal="true"
                                   class="btn btn-default btn-flat menu_load_panel"
                                   title="Ver Perfil de Usuario">Perfil de Usuario</a>
                            </div>
                            <div class="pull-right">
                                <a href="{% url 'usuario:logout' %}"
                                   class="btn btn-default btn-flat"
                                   title="Salir del Sistema">Cerrar Sesi&oacute;n</a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>